import type { Metadata } from "next";
import "./globals.css";
import { MainLayout } from "@/application/layouts/MainLayout";
import { AppProviders } from "@/application/providers";
import { AuthProvider } from "@/providers/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <AuthProvider>
          <AppProviders>
            <MainLayout>{children}</MainLayout>
          </AppProviders>
        </AuthProvider>
      </body>
    </html>
  );
}
